// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

// Package web is scout's third surface: a local application that starts
// runs, streams their progress and renders their reports in a browser.
//
// It is a peer of the CLI and the TUI, not a viewer of them. It builds the
// same engine.RunSpec, calls the same engine.Run, and draws the same
// events, so a run started here is byte-identical to the same run started
// from a flag. The shell it serves is generated by the SSG from the Scout
// theme and embedded in the binary, so the tool is one file with no assets
// to lose and nothing to fetch at runtime.
package web

import (
	"context"
	"crypto/rand"
	"crypto/subtle"
	"embed"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/sebastienrousseau/scout/internal/engine"
	"github.com/sebastienrousseau/scout/internal/report"
)

// dist holds the SSG-generated application shell. The build is committed so
// the binary needs no toolchain at run time; see web/README.md.
//
//go:embed all:dist
var dist embed.FS

// Options configures the server.
type Options struct {
	// Addr is the listen address. It defaults to loopback, and binding
	// anywhere else requires AllowRemote, because this listener can start
	// authenticated requests against other people's servers.
	Addr string
	// AllowRemote permits a non-loopback bind. Off by default.
	AllowRemote bool
	// Version is the scout build, recorded in every report.
	Version string
	// MaxRuns bounds how many reports are held in memory.
	MaxRuns int
	// Open, when set, is called with the URL once the listener is up.
	Open func(string)

	// Public turns on the posture described in public.go: no credentials
	// are accepted, only Allowed targets may be scanned, requests are rate
	// limited, and no token is required because the whole point is that
	// anyone may use it.
	Public bool
	// Allowed is the set of servers a public deployment may scan. Public
	// mode refuses to start without one.
	Allowed *Allowlist
	// RatePerMinute and RateBurst bound one caller's share of a public
	// deployment.
	RatePerMinute int
	RateBurst     int
	// TrustProxyHeader honours X-Forwarded-For for rate limiting. Only set
	// it when a proxy you control is in front, because otherwise a caller
	// can mint a fresh identity per request.
	TrustProxyHeader bool

	// AllowStdio permits a posted run to name a program to execute instead
	// of a URL to fetch. Off by default, and it stays off in Public mode
	// whatever this says.
	//
	// The engine can diagnose a stdio server, and the CLI does. Reaching
	// that through an HTTP request is a different capability: "diagnose the
	// URL in this field" and "run this command on the machine scout is
	// running on" are not the same permission, and a listener that accepts
	// the second is a remote shell with a report attached. The token in the
	// URL bar is not a credential anyone should be able to trade for that,
	// so this is an explicit, separate decision by whoever started the
	// process.
	AllowStdio bool
}

// DefaultMaxRuns is how many finished runs are kept.
const DefaultMaxRuns = 50

// Server is the running application.
type Server struct {
	opts  Options
	token string
	mux   *http.ServeMux

	limit *limiter

	mu    sync.Mutex
	runs  map[string]*run
	order []string
}

// run is one diagnostic and everything a browser can ask about it.
type run struct {
	id     string
	spec   engine.RunSpec
	cancel context.CancelFunc

	mu      sync.Mutex
	events  []engine.Event
	subs    map[chan engine.Event]struct{}
	done    bool
	result  *engine.Result
	failure string
}

// New builds a server. It does not listen.
func New(opts Options) (*Server, error) {
	if opts.Addr == "" {
		opts.Addr = "127.0.0.1:0"
	}
	if opts.MaxRuns <= 0 {
		opts.MaxRuns = DefaultMaxRuns
	}
	host, _, err := net.SplitHostPort(opts.Addr)
	if err != nil {
		return nil, fmt.Errorf("web: invalid address %q: %w", opts.Addr, err)
	}
	if !opts.AllowRemote && !isLoopback(host) {
		return nil, fmt.Errorf("web: refusing to bind %s. This listener starts authenticated requests "+
			"against servers of your choosing and holds their reports; on a shared network anyone who can "+
			"reach it can do both. Pass --allow-remote if that is genuinely what you want", opts.Addr)
	}

	if opts.Public {
		// A public server with no allowlist is an open relay: anyone could
		// aim it at anything the host can route to. Refusing at startup is
		// the only place this can be caught before it matters.
		if opts.Allowed == nil || len(opts.Allowed.Endpoints()) == 0 {
			return nil, fmt.Errorf("web: --public needs an allowlist of servers it may scan; " +
				"without one this listener would send requests anywhere it was asked to")
		}
	}

	tok, err := newToken()
	if err != nil {
		return nil, err
	}
	s := &Server{opts: opts, token: tok, mux: http.NewServeMux(), runs: map[string]*run{}}
	if opts.Public {
		s.limit = newLimiter(opts.RatePerMinute, opts.RateBurst)
	}
	s.routes()
	return s, nil
}

// Token is the value that must appear on every request.
func (s *Server) Token() string { return s.token }

func newToken() (string, error) {
	var b [24]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b[:]), nil
}

func isLoopback(host string) bool {
	if host == "localhost" || host == "" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

func (s *Server) routes() {
	shell, err := fs.Sub(dist, "dist")
	if err != nil {
		// The embed is a build-time fact; a failure here is a broken binary.
		panic("web: embedded shell is unreadable: " + err.Error())
	}
	s.mux.Handle("GET /", http.FileServerFS(shell))
	s.mux.HandleFunc("POST /api/runs", s.startRun)
	s.mux.HandleFunc("GET /api/runs/{id}/events", s.streamRun)
	s.mux.HandleFunc("GET /api/runs/{id}/report.json", s.reportJSON)
	s.mux.HandleFunc("GET /runs/{id}/report.html", s.reportHTML)
	s.mux.HandleFunc("DELETE /api/runs/{id}", s.cancelRun)
}

// ServeHTTP applies the guards every request must pass, then routes.
//
// scout tells every MCP server to validate Origin against DNS rebinding and
// to bind loopback. A diagnostic that does not follow its own advice has no
// standing to give it, so the same two rules are enforced here.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if origin := r.Header.Get("Origin"); origin != "" && !s.sameOrigin(origin, r.Host) {
		http.Error(w, "cross-origin request refused", http.StatusForbidden)
		return
	}
	// A public deployment has no token to check: it exists to be used by
	// people who were never handed one. Origin validation above still
	// applies, and everything a caller could do with it is bounded by the
	// allowlist and the limiter rather than by knowing a secret.
	if !s.opts.Public && !s.authorized(r) {
		http.Error(w, "missing or invalid token", http.StatusUnauthorized)
		return
	}
	// A page authorised by the token in its URL hands that token to the
	// browser as a cookie, so the stylesheet, the scripts and every later
	// fetch carry it too.
	//
	// Without this the printed URL loads the HTML and nothing else: a
	// browser does not append a query string to a subresource, so every
	// asset came back 401 — and because a 401 body is text/plain, the
	// console blamed the MIME type rather than the authorization. authorized
	// already read this cookie; nothing ever set it.
	if !s.opts.Public && r.URL.Query().Get("t") != "" {
		//nolint:gosec // G124: Secure is conditional below, and cannot be
		// unconditional — see the comment on the field.
		http.SetCookie(w, &http.Cookie{
			Name:     "scout_token",
			Value:    s.token,
			Path:     "/",
			HttpOnly: true,
			SameSite: http.SameSiteStrictMode,
			// Set only when the connection is actually TLS. The default
			// listener is loopback http, where a Secure cookie is never
			// stored by the browser at all — so hardcoding it true would
			// re-break every asset this cookie exists to authorise. Behind
			// a TLS terminator (--allow-remote), r.TLS is set and the flag
			// goes on.
			Secure: r.TLS != nil,
		})
	}
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Referrer-Policy", "no-referrer")
	s.mux.ServeHTTP(w, r)
}

func (s *Server) sameOrigin(origin, host string) bool {
	u := strings.TrimPrefix(strings.TrimPrefix(origin, "https://"), "http://")
	return strings.EqualFold(u, host)
}

// authorized accepts the token from the query string (which is how the
// printed URL carries it) or from a header (which is how fetch carries it
// once the page has it).
func (s *Server) authorized(r *http.Request) bool {
	got := r.URL.Query().Get("t")
	if got == "" {
		got = r.Header.Get("X-Scout-Token")
	}
	if got == "" {
		if c, err := r.Cookie("scout_token"); err == nil {
			got = c.Value
		}
	}
	return subtle.ConstantTimeCompare([]byte(got), []byte(s.token)) == 1
}

// Serve listens and blocks until ctx is done.
func (s *Server) Serve(ctx context.Context) error {
	var lc net.ListenConfig
	ln, err := lc.Listen(ctx, "tcp", s.opts.Addr)
	if err != nil {
		return err
	}
	url := fmt.Sprintf("http://%s/?t=%s", ln.Addr().String(), s.token)
	if s.opts.Open != nil {
		s.opts.Open(url)
	}
	srv := &http.Server{
		Handler:           s,
		ReadHeaderTimeout: 10 * time.Second,
		// No write timeout: an SSE stream is meant to stay open for the
		// length of a run, and a run is meant to take as long as the
		// server under test takes.
		IdleTimeout: 120 * time.Second,
	}
	go func() {
		<-ctx.Done()
		// Shutdown needs a context that outlives the cancelled one, but
		// should still carry its values: WithoutCancel is exactly that.
		sctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 3*time.Second)
		defer cancel()
		_ = srv.Shutdown(sctx)
	}()
	if err := srv.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
		return err
	}
	return nil
}

// --- runs -----------------------------------------------------------------

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func (s *Server) startRun(w http.ResponseWriter, r *http.Request) {
	if s.limit != nil && !s.limit.allow(clientKey(r, s.opts.TrustProxyHeader)) {
		w.Header().Set("Retry-After", "30")
		writeJSON(w, http.StatusTooManyRequests, map[string]string{
			"error": "too many runs from this address; wait a moment and try again",
		})
		return
	}
	var spec engine.RunSpec
	dec := json.NewDecoder(http.MaxBytesReader(w, r.Body, 1<<20))
	if err := dec.Decode(&spec); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "the request body is not a run specification: " + err.Error()})
		return
	}
	// A spec naming a program is refused before anything else looks at it.
	// Public mode never permits one; a local server permits it only when
	// the operator said so when starting the process.
	if spec.Target.Stdio() && (s.opts.Public || !s.opts.AllowStdio) {
		writeJSON(w, http.StatusForbidden, map[string]string{
			"error": "this server diagnoses endpoints, not programs. Running a command is a different " +
				"permission from fetching a URL, and it is not one an HTTP request can claim here: " +
				"use the command line — scout check --stdio -- <command> — or start the server with --allow-stdio.",
		})
		return
	}
	if s.opts.Public {
		// Refuse before running, rather than quietly dropping what was
		// sent. A caller who believes their credential was used and is
		// told nothing would reasonably read the result as a test of an
		// authenticated server.
		if used := credentialFieldsSet(spec.Creds); len(used) > 0 {
			writeJSON(w, http.StatusBadRequest, map[string]string{
				"error": "this server accepts no credentials: remove " + strings.Join(used, ", ") +
					". Run scout locally to test a server that needs one — it is the same binary.",
			})
			return
		}
		name, ok := s.opts.Allowed.Permits(spec.Target.Endpoint)
		if !ok {
			writeJSON(w, http.StatusForbidden, map[string]string{
				"error": "this server only scans the endpoints it was started with. " +
					"Run scout locally to test your own server — it is the same binary.",
			})
			return
		}
		_ = name
		// Constructed, not sanitised: whatever arrived is discarded.
		spec = publicSpec(spec)
	}

	spec.Version = s.opts.Version
	spec = spec.WithDefaults()
	// One validator for every surface, so a browser gets the CLI's error.
	if err := spec.Validate(); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}

	id, err := newToken()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	ctx, cancel := context.WithCancel(context.Background())
	rn := &run{id: id, spec: spec, cancel: cancel, subs: map[chan engine.Event]struct{}{}}

	s.mu.Lock()
	s.runs[id] = rn
	s.order = append(s.order, id)
	for len(s.order) > s.opts.MaxRuns {
		delete(s.runs, s.order[0])
		s.order = s.order[1:]
	}
	s.mu.Unlock()

	go func() {
		defer cancel()
		res := engine.Run(ctx, spec, engine.SinkFunc(rn.publish))
		rn.finish(res)
	}()

	writeJSON(w, http.StatusAccepted, map[string]string{"id": id})
}

func (s *Server) lookup(r *http.Request) *run {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.runs[r.PathValue("id")]
}

func (s *Server) cancelRun(w http.ResponseWriter, r *http.Request) {
	rn := s.lookup(r)
	if rn == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "no such run"})
		return
	}
	rn.cancel()
	writeJSON(w, http.StatusAccepted, map[string]string{"status": "cancelling"})
}

func (s *Server) reportJSON(w http.ResponseWriter, r *http.Request) {
	rn := s.lookup(r)
	if rn == nil || rn.report() == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "no report for that run"})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(rn.report())
}

// reportHTML renders the full report server-side.
//
// Rendering here rather than in the browser is deliberate: the report is
// full of strings a server under test chose, and html/template's escaping
// is what keeps them text. It is also the page that prints to PDF.
func (s *Server) reportHTML(w http.ResponseWriter, r *http.Request) {
	rn := s.lookup(r)
	rep := rn.report()
	if rn == nil || rep == nil {
		http.Error(w, "no report for that run", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	verbose := r.URL.Query().Get("verbose") != ""
	if err := report.HTML(w, rep, report.HTMLOptions{Verbose: verbose}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// streamRun delivers the run's events as they land, replaying anything the
// browser missed so a reload does not lose the first phases.
func (s *Server) streamRun(w http.ResponseWriter, r *http.Request) {
	rn := s.lookup(r)
	if rn == nil {
		http.Error(w, "no such run", http.StatusNotFound)
		return
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	w.WriteHeader(http.StatusOK)

	backlog, ch, finished := rn.subscribe()
	defer rn.unsubscribe(ch)

	send := func(v any) bool {
		b, err := json.Marshal(v)
		if err != nil {
			return true
		}
		if _, err := fmt.Fprintf(w, "data: %s\n\n", b); err != nil {
			return false
		}
		flusher.Flush()
		return true
	}
	for _, e := range backlog {
		if !send(e) {
			return
		}
	}
	if finished {
		send(rn.doneEvent())
		return
	}

	keepalive := time.NewTicker(20 * time.Second)
	defer keepalive.Stop()
	for {
		select {
		case <-r.Context().Done():
			return
		case <-keepalive.C:
			if _, err := fmt.Fprint(w, ": keep-alive\n\n"); err != nil {
				return
			}
			flusher.Flush()
		case e, open := <-ch:
			if !open {
				send(rn.doneEvent())
				return
			}
			if !send(e) {
				return
			}
		}
	}
}

// --- run bookkeeping ------------------------------------------------------

func (r *run) publish(e engine.Event) {
	r.mu.Lock()
	r.events = append(r.events, e)
	subs := make([]chan engine.Event, 0, len(r.subs))
	for c := range r.subs {
		subs = append(subs, c)
	}
	r.mu.Unlock()
	for _, c := range subs {
		// Never block the diagnostic on a slow reader: a browser that
		// cannot keep up loses events, not the run.
		select {
		case c <- e:
		default:
		}
	}
}

func (r *run) finish(res *engine.Result) {
	r.mu.Lock()
	r.done, r.result = true, res
	if res != nil && res.Err != nil {
		r.failure = res.Err.Error()
	}
	subs := make([]chan engine.Event, 0, len(r.subs))
	for c := range r.subs {
		subs = append(subs, c)
	}
	r.subs = map[chan engine.Event]struct{}{}
	r.mu.Unlock()
	for _, c := range subs {
		close(c)
	}
}

func (r *run) subscribe() ([]engine.Event, chan engine.Event, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	backlog := make([]engine.Event, len(r.events))
	copy(backlog, r.events)
	if r.done {
		return backlog, nil, true
	}
	ch := make(chan engine.Event, 256)
	r.subs[ch] = struct{}{}
	return backlog, ch, false
}

func (r *run) unsubscribe(ch chan engine.Event) {
	if ch == nil {
		return
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	delete(r.subs, ch)
}

func (r *run) report() *report.Report {
	if r == nil {
		return nil
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.result == nil {
		return nil
	}
	return r.result.Report
}

// doneEvent is the closing record: the browser learns the run ended, why if
// it failed, and gets the report without a second request.
func (r *run) doneEvent() map[string]any {
	r.mu.Lock()
	defer r.mu.Unlock()
	out := map[string]any{"type": "done"}
	if r.failure != "" {
		out["error"] = r.failure
	}
	if r.result != nil && r.result.Report != nil {
		rep := *r.result.Report
		rep.Events = nil // the browser has been watching them
		out["report"] = rep
	}
	return out
}
