// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

//go:build ignore

// ssgcheck enforces the invariant that every page scout publishes is
// generated by ssg from a theme in the SSG theme suite.
//
// It checks four things, all without needing ssg or a checkout of the theme,
// because a gate that needs a second repository is a gate that gets skipped:
//
//  1. No tracked HTML outside a layouts directory. A hand-written page is a
//     page the generator does not own and the theme does not style.
//  2. Each site's ssg configuration exists and its template and output
//     directories are the ones the manifest records. A config that quietly
//     moves the output would leave the embedded shell pointing at nothing.
//  3. The ssg version CI installs satisfies every theme's declared minimum.
//  4. Every file in a layouts directory is either shared with the theme or
//     a declared delta with a reason.
//  5. Every local stylesheet and script a built page references exists in
//     that build. ssg fingerprints assets, and a plugin that injects a link
//     to the unfingerprinted name ships a page whose stylesheet 404s — which
//     is exactly what happened: the syntax-highlight CSS was missing from
//     both the site and the embedded shell, silently, because a missing
//     stylesheet renders as an unstyled page rather than as an error.
//
// With -theme DIR it also measures the vendored layouts against the real
// theme and reports what has diverged. That cannot be a CI gate — CI has no
// checkout of the theme — so it reports rather than fails, and -strict makes
// it fail for someone who does have the theme locally.
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/sebastienrousseau/scout/internal/ecosystem"
)

// pagesWorkflow is where the ssg version CI installs is pinned.
const pagesWorkflow = ".github/workflows/pages.yml"

var installedSSG = regexp.MustCompile(`cargo install ssg\b.*--version\s+(\d+\.\d+\.\d+)`)

func main() {
	themeDir := flag.String("theme", "", "path to a checkout of the SSG theme suite, to measure divergence")
	strict := flag.Bool("strict", false, "with -theme, treat an undeclared divergence as a failure")
	flag.Parse()

	var problems []string
	note := func(format string, a ...any) { problems = append(problems, fmt.Sprintf(format, a...)) }

	for _, err := range ecosystem.ValidateSites() {
		note("%v", err)
	}

	problems = append(problems, checkNoStrayHTML()...)
	problems = append(problems, checkConfigs()...)
	problems = append(problems, checkSSGVersion()...)
	problems = append(problems, checkDeltasAreDeclared()...)
	problems = append(problems, checkAssetsResolve()...)

	if *themeDir != "" {
		diverged := measureDivergence(*themeDir)
		if len(diverged) > 0 {
			fmt.Printf("\nssgcheck: %d vendored file(s) differ from the theme:\n", len(diverged))
			for _, d := range diverged {
				fmt.Printf("  %s\n", d)
			}
			fmt.Println("\nA declared delta is a patch on its way upstream. An undeclared one is a\n" +
				"fork nobody decided to make. Design changes belong in the theme.")
			if *strict {
				note("%d undeclared divergence(s) from the theme", len(diverged))
			}
		}
	}

	if len(problems) > 0 {
		for _, p := range problems {
			fmt.Fprintf(os.Stderr, "ssgcheck: %s\n", p)
		}
		fmt.Fprintf(os.Stderr, "\n%d problem(s). Every page scout publishes is generated by ssg from a\n"+
			"theme in the SSG theme suite; see internal/ecosystem/sites.go.\n", len(problems))
		os.Exit(1)
	}
	fmt.Printf("ssgcheck: %d site(s) generated by ssg from the %s theme, %d declared delta(s)\n",
		len(ecosystem.Sites), ecosystem.Sites[0].Theme, len(ecosystem.ThemeDeltas))
}

// localAsset matches a src or href pointing at a stylesheet or script inside
// the built site. Root-relative only: an absolute URL is somebody else's
// server, and the CSP already governs which of those are allowed.
var localAsset = regexp.MustCompile(`(?:src|href)="(/[^"#?]*\.(?:css|js))"`)

// checkAssetsResolve verifies every local stylesheet and script a built page
// references is actually in the build.
//
// Only builds that are committed can be checked, which today is the embedded
// shell; the marketing site's output is gitignored, so it is checked when it
// happens to be there and skipped when it is not. That is the honest bound:
// a gate that demanded a fresh site build would need ssg installed, and a
// gate that needs a toolchain is a gate that gets skipped.
func checkAssetsResolve() []string {
	var out []string
	for _, site := range ecosystem.Sites {
		dir := site.Output
		info, err := os.Stat(dir)
		if err != nil || !info.IsDir() {
			// Not built. For the marketing site that is the normal state.
			continue
		}
		err = filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() || filepath.Ext(path) != ".html" {
				return err
			}
			b, err := os.ReadFile(path) // #nosec G304 -- walking the site's own output
			if err != nil {
				return err
			}
			seen := map[string]bool{}
			for _, m := range localAsset.FindAllStringSubmatch(string(b), -1) {
				ref := m[1]
				if seen[ref] {
					continue
				}
				seen[ref] = true
				if _, err := os.Stat(filepath.Join(dir, strings.TrimPrefix(ref, "/"))); err != nil {
					out = append(out, fmt.Sprintf("%s references %s, which is not in %s: the page ships asking for a file that is not there",
						path, ref, dir))
				}
			}
			return nil
		})
		if err != nil {
			out = append(out, fmt.Sprintf("walking %s: %v", dir, err))
		}
	}
	sort.Strings(out)
	return out
}

// checkNoStrayHTML refuses a tracked HTML file that is not a layout.
//
// Generated output is excluded by looking only at tracked files: dist
// directories are committed for the shell, so they are named explicitly
// rather than guessed at.
func checkNoStrayHTML() []string {
	out, err := exec.Command("git", "ls-files", "*.html").Output()
	if err != nil {
		return []string{fmt.Sprintf("listing tracked HTML: %v", err)}
	}
	var problems []string
	for _, path := range strings.Fields(string(out)) {
		switch {
		case strings.Contains(path, "/_layouts/"):
		case isGeneratedOutput(path):
		case strings.HasPrefix(path, ".github/"):
			// Issue templates and the like are GitHub's, not the site's.
		default:
			problems = append(problems, fmt.Sprintf("%s is a tracked HTML file outside a layouts directory: "+
				"either it belongs in a theme layout or it is not a page scout publishes", path))
		}
	}
	return problems
}

func isGeneratedOutput(path string) bool {
	for _, s := range ecosystem.Sites {
		if strings.HasPrefix(path, s.Output+"/") {
			return true
		}
	}
	// The report template is a Go template compiled into the binary, not a
	// page ssg generates. It is named rather than pattern-matched so that a
	// second one cannot appear unnoticed.
	return path == "internal/report/report.html.tmpl"
}

// checkConfigs verifies each ssg configuration says what the manifest says.
func checkConfigs() []string {
	var problems []string
	for _, s := range ecosystem.Sites {
		b, err := os.ReadFile(s.Config)
		if err != nil {
			problems = append(problems, fmt.Sprintf("site %s: %v", s.Name, err))
			continue
		}
		cfg := string(b)
		for key, want := range map[string]string{"template_dir": s.Layouts, "output_dir": s.Output} {
			got, ok := tomlString(cfg, key)
			switch {
			case !ok:
				problems = append(problems, fmt.Sprintf("%s: no %s", s.Config, key))
			case got != want:
				problems = append(problems, fmt.Sprintf("%s: %s is %q, the manifest says %q", s.Config, key, got, want))
			}
		}
		if _, err := os.Stat(s.Layouts); err != nil {
			problems = append(problems, fmt.Sprintf("site %s: layouts directory %s: %v", s.Name, s.Layouts, err))
		}
	}
	return problems
}

// checkSSGVersion compares the version CI installs to each theme's minimum.
func checkSSGVersion() []string {
	b, err := os.ReadFile(pagesWorkflow)
	if err != nil {
		return []string{fmt.Sprintf("reading %s: %v", pagesWorkflow, err)}
	}
	m := installedSSG.FindStringSubmatch(string(b))
	if m == nil {
		return []string{fmt.Sprintf("%s does not pin an ssg version; the site would build with whatever is current", pagesWorkflow)}
	}
	installed := m[1]
	var problems []string
	for _, s := range ecosystem.Sites {
		if less(installed, s.MinSSG) {
			problems = append(problems, fmt.Sprintf("CI installs ssg %s, and the %s theme needs at least %s",
				installed, s.Theme, s.MinSSG))
		}
	}
	return problems
}

// checkDeltasAreDeclared refuses a declared delta for a file that is not
// there, which is how a manifest becomes fiction.
func checkDeltasAreDeclared() []string {
	var problems []string
	for _, d := range ecosystem.ThemeDeltas {
		s, ok := ecosystem.LookupSite(d.Site)
		if !ok {
			continue // ValidateSites already reported it
		}
		if _, err := os.Stat(filepath.Join(s.Layouts, d.File)); err != nil {
			problems = append(problems, fmt.Sprintf("a delta is declared for %s/%s and the file is not there: %v",
				d.Site, d.File, err))
		}
	}
	return problems
}

// measureDivergence reports vendored layouts that differ from the theme and
// are not declared.
func measureDivergence(themeDir string) []string {
	var out []string
	for _, s := range ecosystem.Sites {
		entries, err := os.ReadDir(s.Layouts)
		if err != nil {
			out = append(out, fmt.Sprintf("%s: %v", s.Layouts, err))
			continue
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			upstream := filepath.Join(themeDir, "themes", s.Theme, "_layouts", e.Name())
			up, err := os.ReadFile(upstream)
			if err != nil {
				if !ecosystem.DeclaredDelta(s.Name, e.Name()) {
					out = append(out, fmt.Sprintf("%s/%s has no counterpart in the theme and is not declared", s.Name, e.Name()))
				}
				continue
			}
			local, err := os.ReadFile(filepath.Join(s.Layouts, e.Name()))
			if err != nil {
				out = append(out, fmt.Sprintf("%s/%s: %v", s.Name, e.Name(), err))
				continue
			}
			if string(up) == string(local) {
				continue
			}
			if !ecosystem.DeclaredDelta(s.Name, e.Name()) {
				out = append(out, fmt.Sprintf("%s/%s differs from the theme and is not declared (%d vs %d lines)",
					s.Name, e.Name(), lines(local), lines(up)))
			}
		}
	}
	return out
}

func lines(b []byte) int { return strings.Count(string(b), "\n") + 1 }

// tomlString reads a top-level `key = "value"` out of an ssg configuration.
// Deliberately not a TOML parser: it reads two keys from a file this
// repository writes, and a dependency for that would be the larger mistake.
func tomlString(cfg, key string) (string, bool) {
	for _, line := range strings.Split(cfg, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "#") || !strings.HasPrefix(line, key) {
			continue
		}
		rest := strings.TrimSpace(strings.TrimPrefix(line, key))
		if !strings.HasPrefix(rest, "=") {
			continue
		}
		v := strings.TrimSpace(strings.TrimPrefix(rest, "="))
		if s, err := strconv.Unquote(v); err == nil {
			return s, true
		}
	}
	return "", false
}

// less compares two dotted versions. Both come from files this repository
// controls, so a malformed one is a problem to report rather than tolerate.
func less(a, b string) bool {
	as, bs := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(as) && i < len(bs); i++ {
		x, errA := strconv.Atoi(as[i])
		y, errB := strconv.Atoi(bs[i])
		if errA != nil || errB != nil {
			return false
		}
		if x != y {
			return x < y
		}
	}
	return len(as) < len(bs)
}
