// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

package ecosystem

import (
	"fmt"
	"strings"
)

// Both of scout's web surfaces are generated by ssg from a theme in the SSG
// theme suite. That is an invariant rather than a habit, and this file is
// where it is written down so a gate can check it.
//
// Two things make it worth recording. The application shell is committed
// build output that nothing regenerates automatically, so a stale copy ships
// silently — it has already happened once, advertising a check count the
// source had long since left behind. And the layouts are vendored, which is
// the right trade (the site builds in CI with nothing but the ssg binary) and
// creates the one real hazard: a vendored copy can quietly become a fork of
// the theme it came from.

// Site is one ssg-generated surface.
type Site struct {
	// Name is how it is referred to in the Makefile and in conversation.
	Name string
	// Config is the ssg configuration, relative to the repository root.
	Config string
	// Layouts is the vendored template directory.
	Layouts string
	// Output is where ssg writes. For the application shell this is
	// embedded into the binary, which is why it is committed.
	Output string
	// Embedded says whether Output is compiled into the binary by
	// go:embed. An embedded output that goes stale ships stale.
	Embedded bool
	// Theme is the theme in the SSG theme suite that these layouts came
	// from, and Upstream is where it lives.
	Theme    string
	Upstream string
	// Revision is the upstream commit the layouts were vendored from. A
	// branch name is not a revision: it makes "which design is this" a
	// question nobody can answer later.
	Revision string
	// MinSSG is the theme's declared minimum ssg version, from its
	// theme.json. The gate checks the version CI installs against it.
	MinSSG string
}

// Sites are scout's ssg surfaces.
var Sites = []Site{
	{
		Name:     "web-shell",
		Config:   "web/ssg.toml",
		Layouts:  "web/_layouts",
		Output:   "internal/web/dist",
		Embedded: true,
		Theme:    "scout",
		Upstream: "https://github.com/sebastienrousseau/ssg-themes.github.io",
		Revision: "e32f60c",
		MinSSG:   "0.0.56",
	},
}

// ThemeDelta is a vendored layout that deliberately differs from the theme
// it came from.
//
// The point of declaring one is that a local patch stays legible as
// temporary. An undeclared difference is a fork nobody decided to make; a
// declared one is a change on its way upstream, with a reason attached.
type ThemeDelta struct {
	// Site is the Site.Name the file belongs to, and File is relative to
	// that site's Layouts directory.
	Site string
	File string
	// Why the local copy differs.
	Reason string
	// Upstreamed records the pull request that removes the need for this
	// delta, or "" while there is not one yet. A delta that has been
	// waiting a long time with nothing here is a fork with a comment on it.
	Upstreamed string
}

// ThemeDeltas are the differences that exist today.
//
// They were measured rather than assumed, and the list is deliberately
// uncomfortable: every entry is a design decision that lives in this
// repository instead of in the theme, which is the opposite of where design
// decisions belong.
var ThemeDeltas = []ThemeDelta{
	{
		Site: "web-shell", File: "base.html",
		Reason: "The shell is served from a binary on the operator's machine, so it carries a stricter Content-Security-Policy and drops the analytics and external font hooks the public theme has.",
	},
	{
		Site: "web-shell", File: "header.html",
		Reason: "Navigation leaves for scoutmcp.io rather than linking local pages that the single-page shell does not have.",
	},
	{
		Site: "web-shell", File: "footer.html",
		Reason: "States that the run is local and nothing is uploaded, which is a product guarantee rather than a theme concern.",
	},
	{
		Site: "web-shell", File: "styles.css",
		Reason: "Adds the run form, the panel and the assurance block — application chrome that has no counterpart in a content theme.",
	},
	{
		Site: "web-shell", File: "app.html",
		Reason: "The application itself. There is no upstream counterpart.",
	},
	{
		Site: "web-shell", File: "app.js",
		Reason: "The application itself. There is no upstream counterpart.",
	},
	{
		Site: "web-shell", File: "index.html",
		Reason: "The shell has one page and no index listing, so the layout is reduced to the application mount point.",
	},
	{
		Site: "web-shell", File: "404.html",
		Reason: "A 404 inside a binary serving one page means the token was wrong, and it says so.",
	},
	{
		Site: "web-shell", File: "styles.styl",
		Reason: "The Stylus source behind styles.css, vendored at an older theme revision than the compiled CSS beside it; reconciling them is upstream work, not a local edit.",
	},

	// The marketing site once carried two more entries, marked RESIDUE:
	// app.html, a layout no content page used, and app.js, the diagnostic
	// application's client half, which base.html loaded on every page of
	// scoutmcp.io even though no page there has a run form. Both are gone,
	// and the declaration went with them — TestSiteManifestIsTrueOfTheWorking
	// Tree is what keeps the two in step, because a delta declared for a file
	// that is not there fails it.
	//
	// The residue is worth remembering for the reason it existed: vendoring a
	// theme copies whatever the theme ships, and the files nothing references
	// are the ones nobody notices. Every entry above says why it differs;
	// anything that cannot say why is residue, not a delta.
}

// ValidateSites reports every way the site manifest contradicts itself.
func ValidateSites() []error {
	var errs []error
	names := map[string]bool{}
	for _, s := range Sites {
		switch {
		case s.Name == "":
			errs = append(errs, fmt.Errorf("a site has no name"))
			continue
		case names[s.Name]:
			errs = append(errs, fmt.Errorf("site %s: listed twice", s.Name))
			continue
		}
		names[s.Name] = true

		for field, value := range map[string]string{
			"config": s.Config, "layouts": s.Layouts, "output": s.Output,
			"theme": s.Theme, "upstream": s.Upstream, "revision": s.Revision, "min ssg version": s.MinSSG,
		} {
			if strings.TrimSpace(value) == "" {
				errs = append(errs, fmt.Errorf("site %s: no %s", s.Name, field))
			}
		}
		// A branch is not a revision. "main" answers "which design is this?"
		// with "whichever one it was that day".
		for _, moving := range []string{"main", "master", "HEAD", "latest"} {
			if strings.EqualFold(s.Revision, moving) {
				errs = append(errs, fmt.Errorf("site %s: revision %q is a moving target, not a revision", s.Name, s.Revision))
			}
		}
	}

	for _, d := range ThemeDeltas {
		if !names[d.Site] {
			errs = append(errs, fmt.Errorf("theme delta for %s/%s names no site in the manifest", d.Site, d.File))
		}
		if strings.TrimSpace(d.Reason) == "" {
			errs = append(errs, fmt.Errorf("theme delta %s/%s has no reason, which makes it a fork rather than a patch", d.Site, d.File))
		}
	}
	return errs
}

// LookupSite returns the site with the given name.
func LookupSite(name string) (Site, bool) {
	for _, s := range Sites {
		if s.Name == name {
			return s, true
		}
	}
	return Site{}, false
}

// DeltasFor returns the declared deltas for one site.
func DeltasFor(site string) []ThemeDelta {
	var out []ThemeDelta
	for _, d := range ThemeDeltas {
		if d.Site == site {
			out = append(out, d)
		}
	}
	return out
}

// DeclaredDelta reports whether a file under a site's layouts directory is a
// declared difference from the theme.
func DeclaredDelta(site, file string) bool {
	for _, d := range ThemeDeltas {
		if d.Site == site && d.File == file {
			return true
		}
	}
	return false
}
