// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

//go:build ignore

// commitlint enforces AGENTS.md section 4 on the commits a change adds.
//
// The rules live in internal/commitlint, which is tested. This is the part
// that talks to git, and it is deliberately forward-only: it lints the range
// a pull request adds and never the history behind it, because rewriting
// published history to satisfy a linter would trade a formatting problem for
// a signature problem.
//
//	go run ./scripts/commitlint.go [range]
//
// The range defaults to origin/main..HEAD.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/sebastienrousseau/scout/internal/commitlint"
)

func main() {
	rng := "origin/main..HEAD"
	if len(os.Args) > 1 && os.Args[1] != "" {
		rng = os.Args[1]
	}

	// %x00 between commits: a commit message contains blank lines, so no
	// newline-based separator is safe.
	//
	// --no-merges is load-bearing rather than tidy. GitHub Actions checks out
	// a synthetic merge commit for a pull request, whose subject is
	// "Merge <sha> into <sha>" — generated by the platform, authored by
	// nobody, and guaranteed to fail the grammar. This gate failed its own
	// first CI run on exactly that. A merge commit's message is not a
	// contributor's to write, so it is not a contributor's to be judged on.
	out, err := exec.Command("git", "log", "--no-merges", "--format=%H%n%B%x00", rng).Output() //nolint:gosec // the range is an operator argument
	if err != nil {
		fmt.Fprintf(os.Stderr, "commitlint: reading %s: %v\n", rng, err)
		os.Exit(1)
	}

	problems, commits := 0, 0
	for _, raw := range strings.Split(string(out), "\x00") {
		msg := strings.TrimLeft(raw, "\n")
		if strings.TrimSpace(msg) == "" {
			continue
		}
		lines := strings.Split(msg, "\n")
		sha, rest := lines[0], lines[1:]
		if len(rest) == 0 {
			continue
		}
		commits++
		short := sha
		if len(short) > 8 {
			short = short[:8]
		}
		for _, p := range commitlint.Lint(rest) {
			fmt.Fprintf(os.Stderr, "commitlint: %s: %s\n", short, p)
			problems++
		}
	}

	if commits == 0 {
		// Not a pass. An empty range means the caller asked the wrong
		// question, and reporting success would hide that.
		fmt.Fprintf(os.Stderr, "commitlint: no commits in %s; nothing was checked\n", rng)
		os.Exit(1)
	}
	if problems > 0 {
		fmt.Fprintf(os.Stderr, "\n%d problem(s) in %d commit(s). AGENTS.md section 4: "+
			"\"<type>: <subject>\" at most %d characters, imperative, body wrapped at %d.\n"+
			"History is never rewritten for this: fix the commits this change adds.\n",
			problems, commits, commitlint.SubjectMax, commitlint.BodyMax)
		os.Exit(1)
	}
	fmt.Printf("commitlint: %d commit(s) in %s satisfy AGENTS.md section 4\n", commits, rng)
}
