// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

//go:build ignore

// specgen writes the published, Apache-2.0 scoring rubric from the Go that
// implements it, and with -check fails when the committed file has drifted.
//
// ADR 0011 puts the rubric under a licence a gateway can adopt. A published
// rubric that disagreed with the scorer would be worse than none, so it is
// derived from report.Rubric, which reads the same variables ComputeScore
// does. The predicate's JSON Schema is generated the same way in
// scout-reporting, from the attestation types that now live there.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/sebastienrousseau/scout/internal/report"
)

const (
	rubricPath = "spec/rubric/rubric-v1.json"
	// comment travels in the file, because JSON has no other place for it.
	comment = "Generated by scripts/specgen from the scout source; do not edit. " +
		"Licensed Apache-2.0 (see REUSE.toml and docs/adr/0011-attestation-format-is-apache.md)."
)

func main() {
	verify := len(os.Args) > 1 && os.Args[1] == "-check"

	want, err := render(struct {
		Comment string `json:"$comment"`
		report.RubricSpec
	}{comment, report.Rubric()})
	if err != nil {
		fail(err)
	}
	if verify {
		got, err := os.ReadFile(rubricPath)
		if err != nil || !bytes.Equal(got, want) {
			fmt.Fprintf(os.Stderr, "specgen: %s out of date with the source; run make spec\n", rubricPath)
			os.Exit(1)
		}
		fmt.Println("specgen: the published rubric matches the source")
		return
	}
	if err := os.MkdirAll(filepath.Dir(rubricPath), 0o755); err != nil { // #nosec G301 -- a docs directory
		fail(err)
	}
	if err := os.WriteFile(rubricPath, want, 0o644); err != nil { // #nosec G306 -- a published file
		fail(err)
	}
	fmt.Printf("specgen: wrote %s\n", rubricPath)
}

func render(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "specgen:", err)
	os.Exit(1)
}
