// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

//go:build ignore

// specgen writes the published, Apache-2.0 halves of the attestation format
// from the Go that implements them, and with -check fails when the committed
// files have drifted.
//
// ADR 0011 puts the predicate schema and the scoring rubric under a licence
// a gateway can adopt. A hand-written schema beside the Go types would be a
// second copy that disagrees the first time a field is added, and a
// published rubric that disagreed with the scorer would be worse than none.
// So both are derived: the rubric from report.Rubric, which reads the same
// variables ComputeScore does, and the schema from the attest types by
// reflection.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/sebastienrousseau/scout/internal/attest"
	"github.com/sebastienrousseau/scout/internal/report"
)

const (
	rubricPath = "spec/rubric/rubric-v1.json"
	schemaPath = "spec/attestation/mcp-evaluation-v1.schema.json"
	// comment travels in each file, because JSON has no other place for it.
	comment = "Generated by scripts/specgen from the scout source; do not edit. " +
		"Licensed Apache-2.0 (see REUSE.toml and docs/adr/0011-attestation-format-is-apache.md)."
)

func main() {
	verify := len(os.Args) > 1 && os.Args[1] == "-check"

	files := map[string]any{
		rubricPath: struct {
			Comment string `json:"$comment"`
			report.RubricSpec
		}{comment, report.Rubric()},
		schemaPath: schema(),
	}

	var drift []string
	for _, path := range []string{rubricPath, schemaPath} {
		want, err := render(files[path])
		if err != nil {
			fail(err)
		}
		if verify {
			got, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(got, want) {
				drift = append(drift, path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { // #nosec G301 -- a docs directory
			fail(err)
		}
		if err := os.WriteFile(path, want, 0o644); err != nil { // #nosec G306 -- a published file
			fail(err)
		}
	}
	if len(drift) > 0 {
		fmt.Fprintf(os.Stderr, "specgen: %s out of date with the source; run make spec\n", strings.Join(drift, " and "))
		os.Exit(1)
	}
	if verify {
		fmt.Println("specgen: the published rubric and predicate schema match the source")
	} else {
		fmt.Printf("specgen: wrote %s and %s\n", rubricPath, schemaPath)
	}
}

func render(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "specgen:", err)
	os.Exit(1)
}

// fixed are values the format pins, keyed by type and JSON field name, so
// the schema says what a valid statement must carry rather than only its
// shape.
var fixed = map[string]map[string]any{
	"Statement":  {"_type": map[string]any{"const": attest.StatementType}, "predicateType": map[string]any{"const": attest.PredicateType}},
	"Evaluation": {"subjectKind": map[string]any{"const": attest.SubjectKindDescriptor}},
	"Target":     {"transport": map[string]any{"type": "string", "enum": []string{"http", "stdio"}}},
	"Verdict":    {"status": map[string]any{"type": "string", "enum": []string{"pass", "warn", "fail", "skip", "info"}}},
}

// schema describes attest.Statement as JSON Schema 2020-12.
func schema() any {
	defs := map[string]any{}
	root := typeSchema(reflect.TypeOf(attest.Statement{}), defs)
	return map[string]any{
		"$schema":  "https://json-schema.org/draft/2020-12/schema",
		"$id":      attest.PredicateType + "/schema.json",
		"$comment": comment,
		"title":    "scout MCP evaluation attestation (in-toto Statement, predicate v1)",
		"$ref":     root["$ref"],
		"$defs":    defs,
	}
}

var timeType = reflect.TypeOf(time.Time{})

func typeSchema(t reflect.Type, defs map[string]any) map[string]any {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == timeType {
		return map[string]any{"type": "string", "format": "date-time"}
	}
	switch t.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice, reflect.Array:
		return map[string]any{"type": "array", "items": typeSchema(t.Elem(), defs)}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": typeSchema(t.Elem(), defs)}
	case reflect.Struct:
		name := t.Name()
		if _, done := defs[name]; !done {
			defs[name] = nil // reserve, so a recursive type terminates
			props := map[string]any{}
			var required []string
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if !f.IsExported() {
					continue
				}
				tag := f.Tag.Get("json")
				jname, opts, _ := strings.Cut(tag, ",")
				if jname == "-" {
					continue
				}
				if jname == "" {
					jname = f.Name
				}
				if v, ok := fixed[name][jname]; ok {
					props[jname] = v
				} else {
					props[jname] = typeSchema(f.Type, defs)
				}
				if !strings.Contains(opts, "omitempty") {
					required = append(required, jname)
				}
			}
			def := map[string]any{"type": "object", "properties": props}
			if len(required) > 0 {
				def["required"] = required
			}
			defs[name] = def
		}
		return map[string]any{"$ref": "#/$defs/" + name}
	}
	fail(fmt.Errorf("no schema mapping for %s", t))
	return nil
}
