# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

name: Stale

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

permissions: {}

jobs:
  stale:
    name: Mark Stale
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10
        with:
          days-before-stale: 60
          days-before-close: 14
          exempt-issue-labels: 'pinned,security,bug'
          exempt-pr-labels: 'pinned,security'
          stale-issue-message: >-
            This issue has had no activity for 60 days and will be closed in
            14 more unless it is updated or labelled `pinned`.
          stale-pr-message: >-
            This pull request has had no activity for 60 days and will be
            closed in 14 more unless it is updated or labelled `pinned`.
